project:
  type: website
  output-dir: docs

website:
  title: "Learn with Isaac"
  site-url: "https://ieadoboe.github.io/quarto-learn"
  description: "Lessons on data science and deep learning."

  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Lessons"
        href: lessons/index.qmd

  sidebar:
    title: "Lessons"
    style: "floating"
    contents:
      # - section: "Data Science"
      #   contents: lessons/data-science/*
      - section: "Deep Learning"
        contents: lessons/deep-learning/*

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    toggle-theme: true # shows light/dark switch
    toc: true
