project:
  type: website
  output-dir: docs
website:
  title: "Not That Deep"
  site-url: "https://ieadoboe.github.io/quarto-learn"
  description: "Learn data science."
  navbar:
    logo: assets/logo.png
    style: "floating"
    toggle-position: right
    pinned: true
    right:
      - text: "Welcome"
        href: index.qmd
      - text: "Lessons"
        href: lessons/index.qmd
      - text: "About Me"
        href: https://ieadoboe.github.io/
        target: _blank
  sidebar:
    title: "Lessons"
    style: "floating"
    contents:
      - section: "Data Science Foundations"
        contents: lessons/beginner/*
      - section: "Neural Networks Fundamentals"
        contents: lessons/intermediate/*
      - section: "Advanced Deep Learning"
        contents: lessons/advanced/*
      - section: "Cutting-Edge Techniques"
        contents: lessons/expert/*

format:
  html:
    theme: flatly
    css: styles.css
    html-math-method: katex
    smooth-scroll: true
    toc: true

jupyter:
  kernelspec:
    name: "quarto-env"
    language: "python"
    display_name: "Python (Quarto Env)"
  python: "/opt/homebrew/Caskroom/miniconda/base/envs/quarto-env/bin/python3"
